site_name: ELIXIR FAIR Lesson Plans
nav:
    - About: index.md
    - Units:
      - "1. FAIR generics": 
        - "Overview": 'units/FAIR-generics/index.md'
        - "1.1 Why FAIR?": 'units/FAIR-generics/topics/1-why-fair.md'
        - "1.2 FAIR vs open data (science)": 'units/FAIR-generics/topics/2-FAIR-vs-open-data.md'
        - "1.3 Data Life Cycle approach to FAIR/FAIR right from the start": 'units/FAIR-generics/topics/3-data-life-cycle-and-FAIR-from-start.md'
        - "1.4 FAIR and/in institutional data policies": 'units/FAIR-generics/topics/4-FAIR-in-data-policies.md'
        - "1.5 Defining FAIR Objectives for a research / scientific project": 'units/FAIR-generics/topics/5-defining-FAIR-objectives-for-projects.md'
        - "1.6 Defining FAIR Objectives for Organisations": 'units/FAIR-generics/topics/6-FAIR-objectives-for-organisations.md'
        - "1.7 Policies and consent": 'units/FAIR-generics/topics/7-policies-and-consent.md'
      - "2. Findable data":
        - "Overview": 'units/findable-data/index.md'
        - "2.1 Data/Repository discovery": 'units/findable-data/topics/1-data-and-repository-discovery.md'
        - "2.2 Findable data": 'units/findable-data/topics/2-findable-data.md'
        - "2.3 Persistent identifiers (PIDs)": 'units/findable-data/topics/3-persistent-identifiers.md'
        - "2.4 Metadata standards": 'units/findable-data/topics/4-metadata-standards.md'
      - "3. Accessible data":
        - "Overview": 'units/accessible-data/index.md'
        - "3.1 Access modes, sensitive data, registered access,  controlled access": 'units/accessible-data/topics/1-data-access.md'
      - "4. Interoperable data":
        - "Overview": 'units/interoperable-data/index.md'
        - "4.1 Linked data and semantic web technologies": 'units/interoperable-data/topics/1-linked-data-and-semantic-web.md'
        - "4.2 M4M workshop": 'units/interoperable-data/topics/2-M4M-workshop.md'
        - "4.3 Data vocabularies and ontologies": 'units/interoperable-data/topics/3-vocabularies-and-ontologies.md'
      - "5. Reusable data":
        - "Overview": 'units/reusable-data/index.md'
        - "5.1 FAIR Data visiting": 'units/reusable-data/topics/1-FAIR-data-visiting.md'
      - "6. FAIR software":
        - "Overview": 'units/FAIR-software/index.md'
        - "6.1 FAIR Software": 'units/FAIR-software/topics/1-FAIR-software.md'
      - "7. Data Repositories and FAIR":
        - "Overview": 'units/data-repositories/index.md'
        - "7.1 Data Repositories and FAIR": 'units/data-repositories/topics/1-repositories-and-FAIR.md'
    - "Contribute":
        - "Style guide": 'contribute/style_guide.md'
theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-FAIR-Converge
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Converge
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards


extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

