site_name: ELIXIR FAIR Lesson Plans
nav:
    - About: index.md
    - Units:
      - "1. FAIR generics": 
        - "Overview": 'units/unit-1/index.md'
        - "1.4 FAIR and/in institutional data policies": 'units/unit-1/topics/topic-4.md'
      # - "2. Findable data": 'units/unit-1/index.md'
      # - "3. Accessible data": 'units/unit-1/index.md'
      # - "4. Interoperable data": 'units/unit-1/index.md'
      # - "5. Reusable data": 'units/unit-1/index.md'
      # - "6. FAIR software": 'units/unit-1/index.md'
theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-FAIR-Converge
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Converge
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards


extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

