site_name: ELIXIR FAIR Lesson Plans
nav:
    - About: index.md
    - Units:
      - 1. FAIR generics: 
        - Overview: 'units/unit-1/index.md'
        - 1.1 Why FAIR?: 'units/unit-1/topic-1.md'
        - 1.2 FAIR vs open data (science): 'units/unit-1/topic-2.md'
        - 1.3 Data Life Cycle approach to FAIR/FAIR right from the start: 'units/unit-1/topic-3.md'
        - 1.4 FAIR and/in institutional data policies: 'units/unit-1/topic-4.md'
        - 1.5 Defining FAIR Objectives for a research / scientific project: 'units/unit-1/topic-5.md'
        - 1.6 Defining FAIR Objectives for Organisations: 'units/unit-1/topic-6.md'
        - 1.7 Policies and consent: 'units/unit-1/topic-7.md'
      - 2. Findable data: 'units/unit-2/index.md'
        - Overview: 'units/unit-2/index.md'
        - 2.1 Data/Repository discovery: 'units/unit-2/topic-1.md'
        - 2.2 Findable data: 'units/unit-2/topic-2.md'
        - 2.3 Persistent identifiers (PIDs): 'units/unit-2/topic-3.md'
        - 2.4 Metadata standards: 'units/unit-2/topic-4.md'
      - 3. Accessible data: 'units/unit-3/index.md'
        - Overview: 'units/unit-3/index.md'
        - 3.1 Access modes, sensitive data, registered access,  controlled access: 'units/unit-3/topic-1.md'
      - 4. Interoperable data: 'units/unit-4/index.md'
        - Overview: 'units/unit-4/index.md'
        - 4.1 Linked data and semantic web technologies: 'units/unit-4/topic-1.md'
        - 4.2 M4M workshop: 'units/unit-4/topic-2.md'
        - 4.3 Data vocabularies and ontologies: 'units/unit-4/topic-3.md'
      - 5. Reusable data: 'units/unit-5/index.md'
        - Overview: 'units/unit-5/index.md'
        - 5.1 FAIR Data visiting: 'units/unit-5/topic-1.md'
      - 6. FAIR software: 'units/unit-6/index.md'
        - Overview: 'units/unit-6/index.md'
        - 6.1 FAIR Software: 'units/unit-6/topic-1.md'
      - 7. Data Repositories and FAIR: 'units/unit-7/index.md'
        - Overview: 'units/unit-7/index.md'
        - 7.1 Data Repositories and FAIR: 'units/unit-7/topic-1.md'
theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-FAIR-Converge
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Converge
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards


extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

